#!/usr/bin/python3

import os
import amulet
import test

import helper

d = amulet.Deployment(series='trusty')
d.add('mysql')
d.add('wordpress')
d.relate('mysql:db', 'wordpress:db')
d.expose('wordpress')
d.add('memcached')

try:
    # Create the deployment described above, give us 900 seconds to do it
    d.setup(timeout=900)
    # Setup will only make sure the services are deployed, related, and in a
    # "started" state. We can employ the sentries to actually make sure there
    # are no more hooks being executed on any of the nodes.
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    # Something else has gone wrong, raise the error so we can see it and this
    # will automatically "FAIL" the test.
    raise

# Shorten the names a little to make working with unit data easier
wp_unit = d.sentry.unit['wordpress/0']
mysql_unit = d.sentry.unit['mysql/0']

# WordPress requires user input to "finish" a setup. This code is contained in
# the helper.py file found in the lib directory. If it's not able to complete
# the WordPress setup we need to quit the test, not as failed per se, but as a
# SKIPed test since we can't accurately setup the environment
try:
    helper.finish_setup(wp_unit.info['public-address'], password='amulet-test')
except:
    amulet.raise_status(amulet.SKIP, msg="Unable to finish WordPress setup")

home_page = test.get('http://%s/' % wp_unit.info['public-address'], proxies=None)
home_page.raise_for_status() # Make sure it's not 5XX error

d.relate('wordpress:cache', 'memcached:cache')

# Since we've changed the schema of our deployment, we need to run setup again

try:
    # Default timeout should be enough time to get memcached up and related
    d.setup()
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Memcached wasn't stood up in time.")
except:
    # Incase deployer throws an error
    raise

# Verify WordPress still responds with a 200
home_page = test.get('http://%s/' % wp_unit.info['public-address'], proxies=None)
home_page.raise_for_status()

# Verify the WordPress plugin was installed correctly
wp_unit.directory('/var/www/wp-content/plugins/wp-ffpc')
