#!/bin/sh -ex

memcache_host=`relation-get private-address`
memcache_port=`relation-get port`
memcache_port=${memcache_port:-11211}

rm -f .memcache

if [ -z $memcache_port ]; then
    juju-log "Info hasn't been received from the instance yet, exiting silently"
    exit 0
fi

cat > .memcache <<EOF
#!/bin/bash
CACHE_HOST=$memcache_host
CACHE_PORT=$memcache_port

EOF

hooks/config-changed
